"""Initial migration

Revision ID: 3ca733d8cebc
Revises: 
Create Date: 2024-06-18 16:12:50.021476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca733d8cebc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('birthdate', sa.String(length=120), nullable=True))
    op.alter_column('person', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.create_unique_constraint(None, 'person', ['birthdate'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    op.alter_column('person', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('person', 'birthdate')
    # ### end Alembic commands ###
