"""add indexing for name in person

Revision ID: 871b99e14d20
Revises: 3ca733d8cebc
Create Date: 2024-06-18 16:20:22.637623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871b99e14d20'
down_revision: Union[str, None] = '3ca733d8cebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('person_name_key', 'person', type_='unique')
    op.create_index(op.f('ix_person_name'), 'person', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_name'), table_name='person')
    op.create_unique_constraint('person_name_key', 'person', ['name'])
    # ### end Alembic commands ###
