"""add table users, people

Revision ID: d13e2126d43a
Revises: 871b99e14d20
Create Date: 2024-06-18 17:07:06.499610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd13e2126d43a'
down_revision: Union[str, None] = '871b99e14d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('birthdate', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('birthdate'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_people_name'), 'people', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_person_name', table_name='person')
    op.drop_table('person')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('birthdate', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='person_pkey'),
    sa.UniqueConstraint('birthdate', name='person_birthdate_key'),
    sa.UniqueConstraint('email', name='person_email_key')
    )
    op.create_index('ix_person_name', 'person', ['name'], unique=True)
    op.drop_table('users')
    op.drop_index(op.f('ix_people_name'), table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###
